In [1]:
import pandas as pd
import numpy  as np

In [2]:
df = pd.DataFrame({
    'Name'  :['Alice', 'Bob', None, 'Dave', 'Eve'],
    'Age'   :[28, np.nan, 29, 42, 31],
    'Salary':[85000, 72000, np.nan, 105000, 68000],
    'City'  :['Mumbai','Delhi','Bangalore', np.nan,'Pune'],
    'Rating':[4.5, np.nan, 3.8, 4.9, np.nan]
})

In [4]:
df.isnull()

    Name    Age  Salary   City  Rating
0  False  False   False  False   False
1  False   True   False  False    True
2   True  False    True  False   False
3  False  False   False   True   False
4  False  False   False  False    True

In [5]:
df.isna()

    Name    Age  Salary   City  Rating
0  False  False   False  False   False
1  False   True   False  False    True
2   True  False    True  False   False
3  False  False   False   True   False
4  False  False   False  False    True

In [6]:
df.notnull()

    Name    Age  Salary   City  Rating
0   True   True    True   True    True
1   True  False    True   True   False
2  False   True   False   True    True
3   True   True    True  False    True
4   True   True    True   True   False